### ISSUE TITLE
Feature: User can create a game

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/ajax-project#1]
## 💰 Motivation

The user needs to be able to create a game by selecting a category and difficulty level.

## 📐 Plan

Create a responsive form which allows a user to select any category and three difficulties.

## ✅ Task List

- [x] Add header with logo and brand title.
- [x] Add footer with credits logo, and GitHub logo, and contact logo. 
- [x] Add fonts and colors to CSS.
- [x] Add `div[data-view='create-game'] to the HTML.
- [x] Add form for creating the game to div of data-view=['create-game'].
- [x] Add input buttons for all categories from trivia API.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for 'input' events on the category buttons.
- [x] Add input buttons for difficulty levels
- [x] Listen for 'click' events on category buttons to trigger a view swap to difficulty buttons
- [x] Assign difficulty buttons to store difficulty level from trivia API
- [x] Assign category buttons to store category ID from trivia API
- [x] Retrieve and set token session from trivia API
- **Clean Up**
- [x] Confirm that the user interface looks nice on both mobile and desktop screens.
- [x] Remove all CSS properties with no effect.
- [x] Confirm that all previous functionality still works without errors.
