### ISSUE TITLE
Feature: User can answer question

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/ajax-project#2]
## 💰 Motivation

The user needs to be able to answer the quiz question and see whether they answered correctly or incorrectly.

## 📐 Plan

Display one question by pulling from API and give user ability to answer. Then display whether user got question correct (green) or incorrect (red). Highlight correct answer.

## ✅ Task List

- [x] Create DOM tree for quiz question from trivia API
- [x] Render multiple choice quiz question when game form is submitted
- [x] Create new form for user quiz
- [x] Randomize how quiz questions are displayed to user
- [x] Use global data model to store results from trivia API
- [x] Add 'click' event listener for answer buttons
- [x] Create function to check if user selection is correct 
- [x] Render true or false quiz question when game form is submitted
- [x] Create function to check if user selection for true/false is correct 
- [x] Create DOM tree for correct or incorrect text
- [x] Display whether user answered correctly or incorrectly
- [x] Ensure buttons are styled based on correct and incorrect choices.
- **Clean Up**
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
