### ISSUE TITLE
Feature: User can take quiz

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/ajax-project#3]
## 💰 Motivation

The user needs to be able to complete the entire quiz.

## 📐 Plan

Generate a new DOM tree for a new question and delete the previous DOM tree for the previous question. Keep correct answer displayed on screen for a few seconds.

## ✅ Task List

- [x] Create function to delete DOM trees
- [x] Ensure previous question's DOM tree is deleted
- [x] Add DOM deletion when brand title is clicked
- [x] Add setTimeout() to do DOM tree deletion
- [x] Add render function for quiz question
- [x] Clear data model when brand title is clicked
- [x] Reset game form when brand title is clicked
- [x] Create function that renders next question
- **Clean Up**
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
