### ISSUE TITLE
Feature: User can see score

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/ajax-project#4]
## 💰 Motivation

The user needs to be able to see how well they did after taking the quiz

## 📐 Plan

Create a counter for correct and incorrect answers, which updates when the user answers a question. Display a message and final score after last question is answered.

## ✅ Task List

- [x] Add properties for correct and incorrect answers to the data model
- [x] Create function that calculates total score
- [x] Add render function for quiz message
- [x] Add render function for quiz score
- [x] Ensure score is displayed after final question is answered
- [x] Ensure brand title click removes score
- **Clean Up**
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
