### ISSUE TITLE
Feature: User can set a time limit to answer question

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/ajax-project#5]
## 💰 Motivation

The user needs to be able to challenge themselves even more by putting a time limit to answer each quiz question.

## 📐 Plan

Add another section on the form that controls time limit. Then display countdown for each question based on the user's selection.

## ✅ Task List

- [x] Ensure answer buttons can only be clicked once by the user
- [x] Add a new section on the game form to allow user to select time limit
- [x] Add HTML for the countdown timer
- [x] Handle view swap for time limit selection
- [x] Create a function that counts down for each question
- [x] Change question count to match trivia API database
- [x] Reset timer before new question is displayed
- [x] Add time's up message and remove answer clicks when timer is 0
- [x] Ensure correct answer is highlighted once timer is 0
- [x] Trigger view swap after correct answer is displayed
- [x] Add function to skip user selections if not enough API questions
- **Clean Up**
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
